/**
 * Setup wizard planning layer (Phase 5) — the pure half of what setup.sh
 * used to do with sed and cp. Given the wizard's answers, produce a
 * deterministic install plan (copies, template edits, secret writes) that
 * the executor applies with real fs. Every decision the bash script made
 * lives here, testable.
 */
import { existsSync, lstatSync, readlinkSync, statSync } from 'node:fs'
import { posix } from 'node:path'

export type Platform = 'Telegram' | 'Slack' | 'Discord' | 'Teams'
export type EmailProvider = 'Gmail' | 'Outlook/Microsoft 365' | 'Both' | 'Skip for now'

/**
 * How the assistant pays for thinking. 'subscription' runs the bundled Claude
 * engine against an interactive sign-in; 'api-key' drives a provider API
 * directly and never signs in; 'later' leaves .env commented for both, which
 * is honest but produces an assistant that cannot answer until someone
 * returns to it.
 */
export type EngineChoice = 'subscription' | 'api-key' | 'later'
export type AiProvider = 'anthropic' | 'openai' | 'google'

export interface Answers {
  ownerName: string
  assistantName: string
  timezone: string
  city: string
  platform: Platform
  engine: EngineChoice
  /** Set only when engine is 'api-key'. */
  aiProvider?: AiProvider
  /** Model id for providers that have no default (openai, google). */
  aiModel?: string
  personalityVibe: string
  ownerBio: string
  emailProvider: EmailProvider
  emailAddress: string
  gmailAddress: string
  gmailAddress2: string
  outlookAddress: string
  outlookAddress2: string
  emailSignature: string
  latitude: string
  longitude: string
  tempUnit: 'celsius' | 'fahrenheit'
  skills: {
    webResearch: boolean
    apollo: boolean
    wordsmith: boolean
    antilibrary: boolean
    notion: boolean
    kanbanzone: boolean
    wordpress: boolean
  }
  keys: {
    perplexity?: string
    apollo?: string
    google?: string
    anthropic?: string
    openai?: string
    notion?: string
    kanbanzone?: string
    kzBoardId?: string
    wpSiteUrl?: string
    wpUsername?: string
    wpAppPassword?: string
    obsidianVaultPath?: string
  }
  projectPath: string
}

/** {{KEY}} substitution; unknown placeholders are blanked (setup.sh parity). */
export function substituteTemplate(text: string, vars: Record<string, string | undefined>): string {
  return text.replace(/\{\{([A-Z_]+)\}\}/g, (_, key: string) => vars[key] ?? '')
}

export function buildEmailSignature(parts: { name: string; title: string; phone: string; email: string }): string {
  return [parts.name, parts.title, parts.phone, parts.email].filter(Boolean).join('\\n')
}

const PLATFORM_ENV: Record<Platform, string[]> = {
  Telegram: ['TELEGRAM_BOT_TOKEN=', 'ALLOWED_CHAT_ID='],
  Slack: ['SLACK_BOT_TOKEN=', 'SLACK_APP_TOKEN=', 'SLACK_ALLOWED_USERS='],
  Discord: ['DISCORD_BOT_TOKEN=', 'DISCORD_ALLOWED_USERS='],
  Teams: ['TEAMS_APP_ID=', 'TEAMS_APP_SECRET=', 'TEAMS_TENANT_ID='],
}

export const PLATFORM_FORMAT_NOTES: Record<Platform, string> = {
  Telegram: '- Telegram supports limited HTML formatting (bold, italic, code, links)',
  Slack: '- Slack supports mrkdwn formatting (bold, italic, code blocks, links, lists)',
  Discord: '- Discord supports Markdown formatting (bold, italic, code blocks, embeds)',
  Teams: '- Teams supports Adaptive Cards and basic Markdown',
}

/** Which key each provider's answer lands in. Mirrors runtime/ai-sdk/provider.ts. */
const PROVIDER_KEY: Record<AiProvider, string> = {
  anthropic: 'ANTHROPIC_API_KEY',
  openai: 'OPENAI_API_KEY',
  google: 'GOOGLE_API_KEY',
}

function providerKeyValue(a: Answers): string {
  if (a.aiProvider === 'openai') return a.keys.openai ?? ''
  if (a.aiProvider === 'google') return a.keys.google ?? ''
  return a.keys.anthropic ?? ''
}

export function buildEnvContent(a: Answers): string {
  const lines = [
    '# AI Assistant Configuration',
    '# Generated by npm run setup',
    '',
    '# Platform credentials (fill in after creating your bot)',
    ...PLATFORM_ENV[a.platform],
    `TIMEZONE=${a.timezone}`,
  ]

  // Every key name already written, so an answer reused across two questions
  // (a Google key for both Wordsmith and the model provider) does not produce
  // two GOOGLE_API_KEY lines, where the later silently wins.
  const emitted = new Set<string>()

  lines.push('', '# How your assistant reaches a model')
  if (a.engine === 'api-key') {
    const provider = a.aiProvider ?? 'anthropic'
    const keyName = PROVIDER_KEY[provider]
    lines.push('AGENT_RUNTIME=ai-sdk', `AI_PROVIDER=${provider}`)
    if (a.aiModel?.trim()) lines.push(`AI_MODEL=${a.aiModel.trim()}`)
    else if (provider !== 'anthropic') lines.push('# AI_MODEL is REQUIRED for this provider, e.g. AI_MODEL=gpt-5', 'AI_MODEL=')
    lines.push(`${keyName}=${providerKeyValue(a)}`)
    emitted.add(keyName)
  } else if (a.engine === 'subscription') {
    lines.push(
      '# Using the Claude subscription signed in on this machine.',
      '# Nothing to set here. To switch to paying per use instead, uncomment:',
      '# AGENT_RUNTIME=ai-sdk',
      '# AI_PROVIDER=anthropic',
      '# ANTHROPIC_API_KEY='
    )
  } else {
    lines.push(
      '# NOT CONFIGURED YET. Your assistant cannot answer until you do one of these.',
      '#',
      '# Option 1 — Claude subscription (Pro or Max): sign in once on this computer.',
      '#   See docs/SETUP-GUIDE.md > Signing in. Nothing to set in this file.',
      '#',
      '# Option 2 — pay per use with an API key: uncomment and fill in.',
      '# AGENT_RUNTIME=ai-sdk',
      '# AI_PROVIDER=anthropic',
      '# ANTHROPIC_API_KEY='
    )
  }

  if (a.skills.wordsmith && !emitted.has('GOOGLE_API_KEY')) {
    lines.push('', '# Wordsmith (Gemini)', `GOOGLE_API_KEY=${a.keys.google ?? ''}`)
    emitted.add('GOOGLE_API_KEY')
  }
  return lines.join('\n') + '\n'
}

export function installedSkillsList(a: Answers): string {
  const list = ['weather', 'decision-log', 'skill-builder']
  if (a.gmailAddress) list.push('gmail')
  if (a.gmailAddress2) list.push('gmail-secondary')
  if (a.outlookAddress) list.push('outlook')
  if (a.outlookAddress2) list.push('outlook-secondary')
  if (a.skills.webResearch) list.push('web-research')
  if (a.skills.apollo) list.push('apollo')
  if (a.skills.wordsmith) list.push('wordsmith')
  if (a.skills.antilibrary) list.push('antilibrary')
  if (a.skills.notion) list.push('notion')
  if (a.skills.kanbanzone) list.push('kanbanzone')
  if (a.skills.wordpress) list.push('wordpress')
  return list.join(', ')
}

export type PlanAction =
  | { type: 'copy'; from: string; to: string }
  | { type: 'edit'; file: string; vars?: Record<string, string>; literals?: Array<{ find: string; replace: string }> }
  | { type: 'template'; from: string; to: string; vars: Record<string, string>; onlyIfMissing?: boolean }
  | { type: 'secret'; path: string; value: string | undefined; note: string }
  | { type: 'chmod-exec'; file: string }

/** Skip when the target (through symlinks) already exists non-empty. */
export function shouldSkipSecret(path: string): boolean {
  let resolved = path
  try {
    if (lstatSync(path).isSymbolicLink()) resolved = readlinkSync(path)
  } catch {
    return false // path itself missing
  }
  try {
    return existsSync(resolved) && statSync(resolved).size > 0
  } catch {
    return false
  }
}

/**
 * How the assistant refers to the machine it lives on, in its own system
 * prompt. Wrong here is worse than vague: an assistant told it runs on a Mac
 * while sitting on a Windows box either contradicts its own instructions out
 * loud, or trusts them and offers `brew` and `launchctl` to someone who has
 * neither. Unknown platforms get the neutral word rather than a guess.
 */
export function hostOsLabel(platform: string): string {
  if (platform === 'darwin') return 'Mac'
  if (platform === 'win32') return 'Windows PC'
  if (platform === 'linux') return 'Linux machine'
  return 'computer'
}

export function buildSkillPlan(a: Answers, home: string, platform: string = process.platform): PlanAction[] {
  const p: PlanAction[] = []
  const identity = { OWNER_NAME: a.ownerName, PROJECT_PATH: a.projectPath }

  // Always-on trio
  p.push({ type: 'copy', from: 'templates/skills/weather', to: 'skills/weather' })
  p.push({
    type: 'edit',
    file: 'skills/weather/manifest.json',
    vars: { LATITUDE: a.latitude, LONGITUDE: a.longitude, TEMP_UNIT: a.tempUnit, TIMEZONE: a.timezone, CITY: a.city },
  })
  p.push({ type: 'copy', from: 'templates/skills/decision-log', to: 'skills/decision-log' })
  p.push({ type: 'edit', file: 'skills/decision-log/SKILL.md', vars: identity })
  p.push({ type: 'edit', file: 'skills/decision-log/manifest.json', vars: identity })
  p.push({
    type: 'template',
    from: 'templates/decisions/log.md',
    to: 'decisions/log.md',
    vars: { OWNER_NAME: a.ownerName },
    onlyIfMissing: true,
  })
  p.push({ type: 'copy', from: 'templates/skills/skill-builder', to: 'skills/skill-builder' })
  p.push({ type: 'copy', from: 'templates/skills/daily-briefing', to: 'skills/daily-briefing' })
  // OWNER_NAME only: the same file is installed on existing machines by
  // syncAlwaysOnSkills(), which can substitute OWNER_NAME and PROJECT_PATH and
  // nothing else. A placeholder setup fills but sync cannot would render
  // literally for every owner who arrived by update rather than fresh install.
  p.push({ type: 'edit', file: 'skills/daily-briefing/SKILL.md', vars: { OWNER_NAME: a.ownerName } })

  const emailSkill = (kind: 'gmail' | 'outlook', address: string, secondary?: string) => {
    p.push({ type: 'copy', from: `templates/skills/${kind}`, to: `skills/${kind}` })
    p.push({ type: 'edit', file: `skills/${kind}/SKILL.md`, vars: { EMAIL_ADDRESS: address } })
    p.push({ type: 'edit', file: `skills/${kind}/manifest.json`, vars: { EMAIL_ADDRESS: address } })
    if (secondary) {
      const names: Record<string, { id: string; name: string }> = {
        gmail: { id: 'gmail', name: 'Gmail & Google Calendar' },
        outlook: { id: 'outlook', name: 'Outlook Email & Calendar' },
      }
      p.push({ type: 'copy', from: `templates/skills/${kind}`, to: `skills/${kind}-secondary` })
      p.push({ type: 'edit', file: `skills/${kind}-secondary/SKILL.md`, vars: { EMAIL_ADDRESS: secondary } })
      p.push({
        type: 'edit',
        file: `skills/${kind}-secondary/manifest.json`,
        vars: { EMAIL_ADDRESS: secondary },
        literals: [
          { find: `"id": "${names[kind].id}"`, replace: `"id": "${names[kind].id}-secondary"` },
          { find: `"name": "${names[kind].name}"`, replace: `"name": "${names[kind].name} (secondary)"` },
        ],
      })
    }
  }
  if (a.gmailAddress) emailSkill('gmail', a.gmailAddress, a.gmailAddress2 || undefined)
  if (a.outlookAddress) emailSkill('outlook', a.outlookAddress, a.outlookAddress2 || undefined)

  if (a.skills.webResearch) {
    p.push({ type: 'copy', from: 'templates/skills/web-research', to: 'skills/web-research' })
    p.push({ type: 'edit', file: 'skills/web-research/SKILL.md', vars: { ...identity, OWNER_BIO: a.ownerBio } })
    p.push({ type: 'edit', file: 'skills/web-research/manifest.json', vars: identity })
    p.push({
      type: 'secret',
      path: posix.join(home, '.perplexity-api-key'),
      value: a.keys.perplexity,
      note: 'write your Perplexity API key to ~/.perplexity-api-key before using the skill',
    })
  }

  if (a.skills.apollo) {
    p.push({ type: 'copy', from: 'templates/skills/apollo', to: 'skills/apollo' })
    p.push({
      type: 'secret',
      path: posix.join(home, '.apollo-api-key'),
      value: a.keys.apollo,
      note: 'write your Apollo API key to ~/.apollo-api-key before using the skill',
    })
  }

  if (a.skills.wordsmith) {
    p.push({ type: 'copy', from: 'templates/skills/wordsmith', to: 'skills/wordsmith' })
    // Key lands in .env via buildEnvContent, not a secret file.
  }

  if (a.skills.antilibrary) {
    p.push({ type: 'copy', from: 'templates/skills/antilibrary', to: 'skills/antilibrary' })
    p.push({
      type: 'edit',
      file: 'skills/antilibrary/SKILL.md',
      vars: { OWNER_NAME: a.ownerName, OBSIDIAN_VAULT_PATH: a.keys.obsidianVaultPath ?? '' },
    })
  }

  if (a.skills.notion) {
    p.push({ type: 'copy', from: 'templates/skills/notion', to: 'skills/notion' })
    p.push({ type: 'edit', file: 'skills/notion/SKILL.md', vars: { OWNER_NAME: a.ownerName } })
    p.push({
      type: 'secret',
      path: posix.join(home, '.config/notion/api_key'),
      value: a.keys.notion,
      note: 'write your Notion integration token to ~/.config/notion/api_key before using the skill',
    })
  }

  if (a.skills.kanbanzone) {
    p.push({ type: 'copy', from: 'templates/skills/kanbanzone', to: 'skills/kanbanzone' })
    p.push({ type: 'edit', file: 'skills/kanbanzone/manifest.json', vars: { PROJECT_PATH: a.projectPath } })
    p.push({ type: 'chmod-exec', file: 'skills/kanbanzone/scripts/kz.py' })
    const config = a.keys.kanbanzone
      ? JSON.stringify(
          a.keys.kzBoardId
            ? { api_key: a.keys.kanbanzone, default_board_id: a.keys.kzBoardId }
            : { api_key: a.keys.kanbanzone },
          null,
          2
        )
      : undefined
    p.push({
      type: 'secret',
      path: posix.join(home, '.config/kanbanzone/config.json'),
      value: config,
      note: 'set your API key in ~/.config/kanbanzone/config.json before using the skill',
    })
  }

  if (a.skills.wordpress) {
    const wp = { WP_SITE_URL: a.keys.wpSiteUrl ?? '', WP_USERNAME: a.keys.wpUsername ?? '', PROJECT_PATH: a.projectPath }
    p.push({ type: 'copy', from: 'templates/skills/wordpress', to: 'skills/wordpress' })
    p.push({ type: 'edit', file: 'skills/wordpress/SKILL.md', vars: { ...wp, OWNER_NAME: a.ownerName } })
    p.push({ type: 'edit', file: 'skills/wordpress/manifest.json', vars: wp })
    p.push({ type: 'edit', file: 'skills/wordpress/wp-api.mjs', vars: { WP_SITE_URL: wp.WP_SITE_URL, WP_USERNAME: wp.WP_USERNAME } })
    p.push({
      type: 'secret',
      path: posix.join(home, '.config/wordpress/app_password'),
      value: a.keys.wpAppPassword,
      note: 'write your WP Application Password to ~/.config/wordpress/app_password before using the skill',
    })
  }

  // Personality lives in its own file, written once and never regenerated.
  // CLAUDE.md below is rebuilt on every setup run (skills list, platform
  // notes, host OS), so anything the owner writes into it dies on the next
  // run. PERSONALITY.md is the part owners actually rewrite, so it gets
  // onlyIfMissing: a re-run or an update refreshes CLAUDE.md around it and
  // leaves their voice alone. CLAUDE.md reaches it via an @PERSONALITY.md
  // import, which Claude Code resolves natively.
  p.push({
    type: 'template',
    from: 'templates/PERSONALITY.md.template',
    to: 'PERSONALITY.md',
    vars: {
      ASSISTANT_NAME: a.assistantName,
      OWNER_NAME: a.ownerName,
      PERSONALITY_VIBE: a.personalityVibe,
    },
    onlyIfMissing: true,
  })

  // CLAUDE.md from template, last (needs the final skills list).
  p.push({
    type: 'template',
    from: 'templates/CLAUDE.md.template',
    to: 'CLAUDE.md',
    vars: {
      ASSISTANT_NAME: a.assistantName,
      OWNER_NAME: a.ownerName,
      PLATFORM: a.platform,
      HOST_OS: hostOsLabel(platform),
      TIMEZONE: a.timezone,
      PROJECT_PATH: a.projectPath,
      INSTALLED_SKILLS: installedSkillsList(a),
      PLATFORM_FORMAT_NOTES: PLATFORM_FORMAT_NOTES[a.platform],
      OWNER_BIO: a.ownerBio,
      EMAIL_SIGNATURE: a.emailSignature,
    },
  })

  return p
}
