/**
 * Session auto-rotation.
 *
 * Long-lived chat sessions accumulate context until the engine has to
 * compact or trim, and that is where flaky turns tend to come from. Rotating
 * on a message-count or age budget starts a fresh session before that point.
 * An optional summary of the outgoing session is generated by the agent
 * itself and stored as a semantic memory, so the memory layer carries the
 * gist forward without the old transcript.
 *
 * Off by default. Enable in .env:
 *   SESSION_MAX_MESSAGES=150      # rotate after this many user turns (0 = off)
 *   SESSION_MAX_AGE_HOURS=48      # rotate when the session is older than this (0 = off)
 *   SESSION_ROTATE_SUMMARY=false  # skip the summary turn (default true)
 */
import { readEnvFile } from './env.js'
import { getSessionMeta, clearSession, insertMemory } from './db.js'
import { logger } from './logger.js'

export type RotationConfig = {
  maxMessages: number
  maxAgeHours: number
  summary: boolean
}

export type SessionMeta = {
  sessionId: string
  createdAt: number
  messageCount: number
}

function readPositiveInt(raw: string | undefined): number {
  const n = Number.parseInt((raw ?? '').trim(), 10)
  return Number.isFinite(n) && n > 0 ? n : 0
}

export function rotationConfig(
  env: Record<string, string | undefined> = { ...readEnvFile(), ...process.env }
): RotationConfig {
  return {
    maxMessages: readPositiveInt(env.SESSION_MAX_MESSAGES),
    maxAgeHours: readPositiveInt(env.SESSION_MAX_AGE_HOURS),
    summary: (env.SESSION_ROTATE_SUMMARY ?? 'true').trim().toLowerCase() !== 'false',
  }
}

export function needsRotation(meta: SessionMeta | null, config: RotationConfig, nowMs = Date.now()): boolean {
  if (!meta) return false
  if (config.maxMessages > 0 && meta.messageCount >= config.maxMessages) return true
  if (config.maxAgeHours > 0 && nowMs - meta.createdAt >= config.maxAgeHours * 3_600_000) return true
  return false
}

export const SUMMARY_PROMPT = [
  'This session is about to be rotated and its transcript will no longer be available to you.',
  'Write a compact handoff summary (under 300 words) of this conversation for your future self:',
  'open tasks and their status, decisions the user made, preferences they expressed, and anything you promised to follow up on.',
  'Plain text, no headers, no preamble. Do not use tools.',
].join(' ')

export type SummaryRunner = (prompt: string, sessionId: string) => Promise<string | null>

/**
 * Rotate the chat's session: optionally summarise the outgoing session into a
 * semantic memory, then drop the session row so the next turn starts fresh.
 * Never throws; a failed summary just means rotation without one.
 */
export async function rotateSession(
  chatId: string,
  config: RotationConfig,
  runSummary: SummaryRunner
): Promise<{ rotated: boolean; summary: string | null }> {
  const meta = getSessionMeta(chatId)
  if (!meta) return { rotated: false, summary: null }

  const ageH = Math.round((Date.now() - meta.createdAt) / 3_600_000)
  logger.info({ chatId, sessionId: meta.sessionId.slice(0, 8), messages: meta.messageCount, ageH }, 'Rotating session')

  let summary: string | null = null
  if (config.summary) {
    try {
      const text = await runSummary(SUMMARY_PROMPT, meta.sessionId)
      if (text && text.trim()) {
        summary = text.trim()
        insertMemory(chatId, `Session handoff (${new Date().toISOString().slice(0, 10)}): ${summary.slice(0, 1500)}`, 'semantic')
      }
    } catch (err) {
      logger.warn({ err, chatId }, 'Session summary failed; rotating without one')
    }
  }

  clearSession(chatId)
  return { rotated: true, summary }
}
